version: 2.1
# orbs:
#   codecov: codecov/codecov@1.1.3
jobs:
    build:
        environment:
            IMAGE_NAME: backend
            DOCKER_LOGIN: csandre
            TAG: latest
        working_directory: ~/repo
        docker:
            - image: circleci/node:erbium
        steps:
            # - codecov/upload:
            #     file: coverage/coverage-final.json
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package-lock.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules
            # Lint the source code
            - run:
                name: Linting
                command: npm run lint
            # Test the source code
            - run:
                name: Testing
                command: npm run test
            - store_artifacts:
                path: coverage
            - setup_remote_docker
            - run:
                name: Build and push Docker image
                command: |
                    docker build -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
                    echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
                    docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG